version: '3'
services:
  one:
    build: './1'
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      - FLASK_APP=main.py
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/mejik

  two:
    build: './2'
    ports:
      - '5001:5001'
    environment:
      - MONGODB_URL=mongodb://nur:aFJaqPF4L6GwUmSG@cluster0-shard-00-00.f5yc9.mongodb.net:27017,cluster0-shard-00-01.f5yc9.mongodb.net:27017,cluster0-shard-00-02.f5yc9.mongodb.net:27017/mejik?ssl=true&replicaSet=atlas-65p6n0-shard-0&authSource=admin&retryWrites=true&w=majority

  three:
    build: './3'
    ports:
      - '5002:5002'
    depends_on:
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://nur:aFJaqPF4L6GwUmSG@cluster0-shard-00-00.f5yc9.mongodb.net:27017,cluster0-shard-00-01.f5yc9.mongodb.net:27017,cluster0-shard-00-02.f5yc9.mongodb.net:27017/mejik?ssl=true&replicaSet=atlas-65p6n0-shard-0&authSource=admin&retryWrites=true&w=majority
      - MAILGUN_KEY=c502a3ef0fea96c0dfc0e4cdb4396288-2af183ba-9cf65057
      - MAILGUN_DOMAIN=sandboxbaab25502b5349ff87a415d6e7ebd5d5.mailgun.org
      - AMQP_URL=amqp://rabbitmq:5672

  four:
    build: './4'
    ports:
      - '5003:5003'
    environment:
      - HOST_ONE=one
      - HOST_TWO=two
      - HOST_THREE=three

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mejik

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  nginx:
    image: nginx:latest
    ports:
      - '6921:6921'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - one
      - two
      - three
      - four
